image: Visual Studio 2017
build_script:
        - ps: $pkage=Get-ChildItem -name *.txt
        $pkagepath="..\dist\"+$pkage
        $pkagepath
#         mkdir build_win &&
#         C:\Python36-x64\Scripts\pip install $pkagepath &&
#         cd build_win
#         cmake -G "Visual Studio 15 Win64" ../ &&
#         MSBuild xLearn.sln /p:Configuration=Release &&
#         cd python-package &&
#         C:\Python36-x64\Scripts\pip install wheel cython &&
#         C:\Python36-x64\python.exe setup.py bdist_wheel --universal --plat-name win_amd64
# test_script:
#         cd ..\test &&
#         .\run_all_test.bat &&
#         cd ..\python-package\test &&
#         $pkage=Get-ChildItem -name ..\dist\*.whl &&
#         $pkagepath="..\dist\"+$pkage &&
#         C:\Python27-x64\Scripts\pip install $pkagepath &&
#         C:\Python27-x64\Scripts\pip install wheel scikit-learn cython &&
#         C:\Python27-x64\python.exe test_data_conversion.py &&
#         C:\Python27-x64\python.exe test_python.py &&
#         C:\Python36-x64\Scripts\pip install $pkagepath &&
#         C:\Python36-x64\Scripts\pip install wheel scikit-learn cython &&
#         C:\Python36-x64\python.exe test_data_conversion.py &&
#         C:\Python36-x64\python.exe test_python.py &&
#         C:\Python35-x64\Scripts\pip install $pkagepath &&
#         C:\Python35-x64\Scripts\pip install wheel scikit-learn cython &&
#         C:\Python35-x64\python.exe test_data_conversion.py &&
#         C:\Python35-x64\python.exe test_python.py &&
#         C:\Python34-x64\Scripts\pip install $pkagepath &&
#         C:\Python34-x64\Scripts\pip install --upgrade setuptools && 
#         C:\Python34-x64\Scripts\pip install wheel scikit-learn cython &&
#         C:\Python34-x64\python.exe test_data_conversion.py &&
#         C:\Python34-x64\python.exe test_python.py        
# artifacts:
#         - path: build_win\Release\*.exe
#           name: Bits
#         - path: build_win\python-package\dist\*.whl
#           name: Bits
